# templates cannot be properly checked for formatting due to the substitution syntax
exclude: templates
repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.12.0
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.334
    hooks:
      - id: pyright
        files: ((plugins\/.*\/src|sphinx_ext)\/.*\.py)|plugin_builder.py
        additional_dependencies:
          [
            pandas,
            deephaven-core,
            'plotly>=5.15.0,<6.0.0',
            json-rpc,
            matplotlib,
            deephaven-plugin-utilities>=0.0.2,
            sphinx,
            click,
            watchdog,
            pyjsonpatch,
            puremagic,
          ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
