repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.12.0
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.334
    hooks:
      - id: pyright
        files: plugins.*\/src.*\.py
        additional_dependencies:
          [
            pandas,
            deephaven-core,
            plotly,
            json-rpc,
            matplotlib
          ]
