name: Make Docs

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      version:
        required: true
        type: string
      event_name:
        required: false
        type: string
        default: 'push'

jobs:
  make-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # assume that the dist artifact is already available from calling build-python-package.yml before this workflow
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist-${{ inputs.package }}
          path: plugins/${{ inputs.package }}/dist/

      - name: Install requirements
        run: pip install -r sphinx_ext/sphinx-requirements.txt

      - name: Install wheel
        run: pip install plugins/${{ inputs.package }}/dist/*.whl

      - name: Run make_docs.py
        run: python plugins/${{ inputs.package }}/make_docs.py

      - name: Setup rclone
        # pull requests should run the make_docs.py script, but not sync the docs
        if: inputs.event_name == 'push'
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

          mkdir -p $HOME/.config
          mkdir -p $HOME/.config/rclone

          cat << EOF > $HOME/.config/rclone/rclone.conf
          [plugindocs]
          type = google cloud storage
          service_account_file = $HOME/credentials.json
          project_number = ${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}
          bucket_policy_only = true
          EOF
          
          echo ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }} | base64 -d > $HOME/credentials.json

      - name: Sync docs
        if: inputs.event_name == 'push'
        run: rclone sync plugins/${{ inputs.package }}/docs/build/markdown/ plugindocs:${{ secrets.GOOGLE_CLOUD_BUCKET }}/deephaven/deephaven-plugins/${{ inputs.package }}/${{ inputs.version }}/
